INFO: Starting training:
        Epochs:          1
        Batch size:      1
        Learning rate:   1e-05
        Training size:   1530
        Validation size: 170
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.3
        Mixed Precision: True



























































































































































































































































Epoch 1/1:  37%|█████████████▉                        | 560/1530 [08:25<14:36,  1.11img/s, loss (batch)=nan]
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe
INFO: Saved interrupt