INFO: Starting training:
        Epochs:          1
        Batch size:      1
        Learning rate:   0.0001
        Training size:   1360
        Validation size: 340
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
        Mixed Precision: True
































































Epoch 1/1:   7%|██▊                                   | 101/1360 [02:10<26:35,  1.27s/img, loss (batch)=nan]Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
Epoch 1/1:   7%|██▊                                   | 101/1360 [02:12<27:28,  1.31s/img, loss (batch)=nan]  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/home/frank/miniconda3/envs/condatest/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe
INFO: Saved interrupt